QsTech.Framework.Web/Modules/QsTech.Accounts/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using QsTech.Accounts.Models.AccountServices;
using QsTech.Accounts.Models.Accounts;
using QsTech.Accounts.Models.Profiles;
using QsTech.Accounts.Models.RoleAccount;
using QsTech.Accounts.Models.SelectAccounts;
using QsTech.Core.Interface;
using QsTech.Core.Interface.Account;
using QsTech.Core.Interface.Clients;
using QsTech.Framework;
using QsTech.Framework.Json;
using QsTech.Framework.Security;
using QsTech.Framework.Pagination;

namespace QsTech.Accounts.Controllers
{
    [NoAuthorize]
    public class ApiController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly IClientManager _clientManager;
        private readonly IEncryption _encryption;

        public ApiController(IAccountService accountService,
            IClientManager clientManager, IEncryption encryption)
        {
            _accountService = accountService;
            _clientManager = clientManager;
            _encryption = encryption;
        }


        protected override void Execute(System.Web.Routing.RequestContext requestContext)
        {
            if (requestContext.HttpContext.Request.HttpMethod == "OPTIONS")
            {
                requestContext.HttpContext.Response.Write("ok");
            }
            else
            {
                base.Execute(requestContext);
            }

        }

        #region 账户选择
        public ActionResult Selector(SelectAccountSearchParameter parameter)
        {
            var datas = _accountService.GetAccounts(parameter);
            ViewBag.Multiable = parameter.Multiable;
            ViewBag.ExcludeArray = parameter.ExcludeArray;
            ViewBag.SearchParameter = parameter;
            return PartialView("SelectorPartial", datas);
        }
        #endregion


        #region 客户端接口
        /// <summary>
        /// 获取账户列表
        /// </summary>
        /// <param name="searchParameter"></param>
        /// <returns></returns>
        public ActionResult GetAccountsData([JsonModelBinder]AccountSearchParameter searchParameter)
        {
           var resultData = new JsonData<PagedListWrapper<Account>>();
           try
           {
               resultData.d = _accountService.GetAccounts(searchParameter).ToPagedListWrapper();
           }
           catch (Exception ex)
           {

               resultData.m = "获取账户信息失败!";
           }
           return this.QsJson(resultData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 获取账户列表
        /// </summary>
        /// <param name="searchParameter"></param>
        /// <returns></returns>
        public ActionResult GetAccountsDataList(AccountSearchNParameter searchParameter)
        {

            try
            {
                var datas = _accountService.GetAccountPagedList(searchParameter);
                if (datas.rows == null)
                    datas.rows = new List<Account>();
                var ndatas =
                    datas.rows.Select(m => new AccountDto() { id = m.Id, accountName = m.AccountName, name = m.Name });
                var pagelList = new QsTech.Accounts.Models.PagedList<AccountDto>(ndatas,searchParameter.pageSize, searchParameter.pageIndex+1, datas.total);
                return this.QsJson(pagelList, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw new QsTechException("获取帐户列表失败!");

            }

        }


        /// <summary>
        /// 添加SSO帐户信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateSsoAccount(CreateAccountModel model)
        {
            var re =new  JsonData<int>();
            try
            {
                if (_accountService.ExistsAccount(model.LoginName))
                {
                    re.s = false;
                    re.m ="帐户名称已存在!";
                    Response.StatusCode = 500;
                    return Json("帐户名称已存在!");
                }
                var newAccount = new Account()
                {
                    AccountName = model.LoginName,
                    Password = model.Password,
                    Name = string.IsNullOrEmpty(model.Name) ? " " : model.Name,
                    Age = model.Age,
                    Birthday = model.Birthday,
                    Gender = model.Gender,
                    Telephone = model.Telephone,
                    Mobile = model.Mobile,
                    Email = model.Email,
                    JobNumber = model.JobNumber,
                };
                _accountService.AddAccount(newAccount);
                re.d = newAccount.Id;
                if (model.Clients != null)
                {
                    _accountService.AuthorizeClients(newAccount.Id, model.Clients);
                }
                return Json(newAccount.Id);
            }
            catch (Exception ex)
            {
                re.s = false;
                Response.StatusCode = 500;
                return Json(ex.Message);
            }
            return Json(re);
        }

        /// <summary>
        /// 修改SSO密码
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateSsoPassword(ChangePasswordModel model)
        {
            var re = new JsonData<bool>();
            try
            {
                if (string.IsNullOrEmpty(model.NewPassword))
                {
                    re.s = false;
                    Response.StatusCode = 500;
                    return Json("新密码不能为空!");
                }
                //var user = _accountService.GetAccountById(model.Id);
                //if (user == null)
                //{
                //    re.s = false;
                //    Response.StatusCode = 500;
                //    return Json("帐户不存在!");
                //}
                _accountService.InitPassword(model.Id,model.NewPassword);
                return Json(true);
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                return Json(ex.Message);
            }           
        }


        /// <summary>
        /// 获取账户信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public  ActionResult GetAccountById(int id)
        {
            var resultData = new JsonData<Account>();
            try
            {
                resultData.d=_accountService.GetAccountById(id);
            }
            catch (Exception ex)
            {

                resultData.m = "获取账户信息失败!";
            }
            return this.QsJson(resultData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 更新账户信息
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateAccount([JsonModelBinder]ClientAccountCreateModel model)
        {

            var resultData = new JsonData<int>();
            try
            {
                if(string.IsNullOrEmpty(model.ApplicationId))
                {
                    resultData.m = string.Format("应用ApplicationId为空!");
                    return this.QsJson(resultData);
                }
                var client = _clientManager.GetClientByApplicationId(model.ApplicationId);
                if(client==null)
                {
                    resultData.m = string.Format("找不到id为{0}的应用!",model.ApplicationId);
                    return this.QsJson(resultData);
                }
                if (_accountService.ExistsAccount(model.Password))
                {
                    resultData.m = string.Format("密码不能为空!");
                    return this.QsJson(resultData);
                }
                if (_accountService.ExistsAccount(model.AccountName))
                {
                    resultData.m = string.Format("账户名{0}已存在!",model.AccountName);
                    return this.QsJson(resultData);
                }
                var account = model.ConvertToEntity();
                _accountService.AddAccount(account);
                _accountService.NewAccountAuthorizeClient(account.Id,client.Id);
                resultData.d = account.Id;
            }
            catch (Exception ex)
            {

                resultData.m = "创建账户失败!";
            }
            return this.QsJson(resultData);
        }


        /// <summary>
        /// 更新账户信息
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateAccount([JsonModelBinder]SsoAccountModel model)
        {
            var resultData = new JsonData<bool>();
            try
            {
                var account = _accountService.GetAccountById(model.Id);
                if (account != null)
                {
                    account.Age = model.Age;
                    account.Name = model.Name;
                    account.Telephone = model.Telephone;
                    account.Mobile = model.Mobile;
                    account.Gender = model.Gender;
                    account.Email = model.Email;
                    _accountService.UpdateAccount(account);
                }
                resultData.d = true;
            }
            catch (Exception ex)
            {
                resultData.m = "更新账户信息失败!";
            }
            return this.QsJson(resultData);
        }

        /// <summary>
        /// 更新账户信息
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteAccount(int id)
        {
            var resultData = new JsonData<bool>();
            try
            {
                var account = _accountService.GetAccountById(id);
                if (account != null)
                {

QsTech.Framework.Web/Modules/QsTech.Accounts/Controllers/RegisterAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QsTech.Accounts.Models.AccountServices;
using QsTech.Accounts.Models.Accounts;
using QsTech.Accounts.Models.Registers;

namespace QsTech.Accounts.Controllers
{
    public class RegisterAccountController : Controller
    {
        private readonly IAccountService _accountService;

        public RegisterAccountController(IAccountService accountService)
        {
            _accountService = accountService;
        }


        #region  申请帐号管理
        public ActionResult List(RegisterAccounSearchParameter searchParameter)
        {
            var data = _accountService.GetRegisterAccounts(searchParameter);
            ViewBag.SearchParameter = searchParameter;
            return View(data);
        }



        public ActionResult View(int id)
        {
            var account = _accountService.GetRegisterAccountById(id);
            var model = new EditAccountModel(account);
            return View(model);

        }

        #endregion


        public ActionResult AuthorizeRegisterAccount(int id)
        {
            var account = _accountService.GetRegisterAccountById(id);
            var model = new CreateAccountModel(account);
            return View(model);
        }

        [HttpPost]
        public ActionResult Authorize(CreateAccountModel model)
        {
            if (ModelState.IsValid)
            {
                if (_accountService.ExistsAccount(model.LoginName))
                {
                    ModelState.AddModelError("LoginName", string.Format("登录账号 {0} 已经存在", model.LoginName));
                    return View("AuthorizeRegisterAccount", model);
                }
                var account = _accountService.GetRegisterAccountById((int)model.Id);
                account.AccountName = model.LoginName;
                account.Password = model.ConfirmPassword;
                account.Name = model.Name;
                account.Age = model.Age;
                account.Birthday = model.Birthday;
                account.Gender = model.Gender;
                account.Telephone = model.Telephone;
                account.Mobile = model.Mobile;
                account.Email = model.Email;
                account.JobNumber = model.JobNumber;
                _accountService.AuditAccount(account);
                return RedirectToAction("Edit","Account", new { id = account.Id});
            }
            return View("AuthorizeRegisterAccount",model);
        }


        #region 删除账户信息
        public ActionResult Delete(int id)
        {
            var account = _accountService.GetRegisterAccountById(id);
            account.Deleted = true;
            _accountService.UpdateRegisterAccount(account);
            return RedirectToAction("List");
        }

        #endregion
    }
}

QsTech.Framework.Web/Modules/QsTech.Accounts/Views/RegisterAccount/AuthorizeRegisterAccount.cshtml
@model QsTech.Accounts.Models.Accounts.CreateAccountModel
@{
    this.ChannelId = "Management";
    ViewBag.Title = "账户申请审核";
}
<div class="rightCont">
    <div class="mt10">
        @using (Html.BeginForm("Authorize", "RegisterAccount"))
        {
            <table style="width:100%; line-height:24px" class="data-detail">
                <tr>
                    <td style="text-align: right;width:88px;">
                        <i class="required">*</i>登录账号：
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.LoginName)
                        @Html.ValidationMessageFor(model => model.LoginName)
                        @Html.HiddenFor(m=>m.Id)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        <i class="required">*</i>登录密码：
                    </td>
                    <td>
                        @Html.PasswordFor(model => model.Password)
                        @Html.ValidationMessageFor(model => model.Password)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        <i class="required">*</i>确认密码：
                    </td>
                    <td>
                        @Html.PasswordFor(model => model.ConfirmPassword)
                        @Html.ValidationMessageFor(model => model.ConfirmPassword)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        <i class="required"></i>姓名：
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        年龄：
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.Age)
                        @Html.ValidationMessageFor(model => model.Age)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        工号：
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.JobNumber)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        性别：
                    </td>
                    <td>
                        @Html.RadioButtonFor(model => model.Gender, "男", new { id = "Gender_0", @class = "radio" })
                        <label for="Gender_0">男</label>
                        @Html.RadioButtonFor(model => model.Gender, "女", new { id = "Gender_1", @class = "radio" })
                        <label for="Gender_1">女</label>
                        @Html.ValidationMessageFor(model => model.Gender)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        生日：
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Birthday, "DateTextBox")
                        @Html.ValidationMessageFor(model => model.Birthday)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        固定电话：
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.Telephone)
                        @Html.ValidationMessageFor(model => model.Telephone)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        <i class="required"></i>移动电话：
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.Mobile)
                        @Html.ValidationMessageFor(model => model.Mobile)
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        <i class="required"></i>电子邮件：
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.Email)
                        @Html.ValidationMessageFor(model => model.Email)
                    </td>
                </tr>
            </table>
            <div class="mt_10 ml_20">
                <input type="submit" value="保 存" class="btn btn-primary" />
               
               <input type="button" value="账户申请列表" class="btn" onclick="javascript:window.location='@Url.Action("List")';" />

            </div>
        }
    </div>
</div>
@section AfterBody
{
@ResourceManager.Include("modalShow").Render()
<script type="text/javascript">
    $(function () {
        $("#Birthday").datepicker({ altFormat: 'yy-mm-dd', yearRange: 'c-50' });



    });
</script>
}

QsTech.Framework.Web/Modules/QsTech.Accounts/Views/RegisterAccount/List.cshtml
@using QsTech.Accounts.Models.Registers
@model QsTech.Framework.Pagination.IPagedList<QsTech.Accounts.Models.Accounts.Account>
@{
    this.ChannelId = "Management";
    ViewBag.Title = "账户申请列表";
    var searchParameter = (RegisterAccounSearchParameter)ViewBag.SearchParameter;
    searchParameter.tips = "姓名";
    //var isSso = (bool)ViewBag.IsSso;
}
<style>
    td label { display: inline-block; }
    table tbody tr { height: 30px; border-bottom: 1px dotted #666; }
    .AttrBox th { text-align: right; }
    .header-nav{ z-index:1000;}
</style>
<div>
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>温馨小贴士：</strong>只需要一分钟，快速了解操作栏的每一项操作功能。
        <ol>
            <li>审核：审核账户的基本信息。</li>
            <li>删除：删除无用的账户申请！</li>

        </ol>
    </div>
    <script type="text/javascript">
        $(".alert-info .close").click(function () {
            $(this).closest('.alert-info').hide();
        });
    </script>
	<input type="button" value="添 加" class="btn" onclick="javascript:window.location='@Url.Action("Create")';" />
    <div class="mt_10 border attr-data">
        <div class="selected-attr" style="height:2px;"></div>
        <table class="AttrBox">
            <tbody>
                <tr>
                    <th style="text-align: right;">
                        关键字：
                    </th>
                    <td style="text-align: left;">
                        @Html.Action("KeyWord", "Api", "QsTech.Core", searchParameter)
                        <input id="btnQuery" type="button" value="查 询" class="btn" />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
	<table style="width:100%;" class="tbl-list">
		<thead>
			<tr class="thead-tbl" style="background-color: #ccc; height: 30px;">
				<th style="width:30px;"></th>
					<th style="text-align:center;width:138px;">姓名</th>
                    <th>移动电话</th>
                    <th>电子邮件</th>
                    <th style=" text-align:center;">操作</th>
			</tr>
		</thead>
		<tbody class="tbody-tbl">
            @if (Model.TotalItemCount > 0)
            {
                int index = 0;
                foreach (var user in Model)
                {
                    index++;
			<tr>
					<td align="center">@index</td>
					<td align="center"><a href="@Url.Action("View", new { id = user.Id })" class="blue">@user.Name</a></td>
                    <td>@user.Mobile</td>
                   <td>@user.Email</td>
					<td style="text-align:center;">
						<a href="@Url.Action("View", new { id = user.Id })" class="a_blue">审核</a>|
						<a name="Delete" href="@Url.Action("Delete", new { id = user.Id })" class="a_blue">删除</a>
                        
                      
                     </td>
				</tr>
                }
            }
            else
            {
            <tr>
                <td align="center" colspan="6">没有符合条件的数据</td>
            </tr>
            }
		</tbody>
	</table>
</div>
<div class="pagination f_r">
    @Html.Pagination(Model)
</div>
<div id="dialog" title="选择账户"></div>
@section AfterBody
{
@ResourceManager.Include("modalShow").Render()
<script type="text/javascript">
    $(function () {
        $("#txtKeyword").enterTo('#btnQuery');
        $("#btnQuery").one('click', function () {
            window.location = "@Url.Action("List")?keyword=" + encodeURIComponent($.trim($("#txtKeyword").val()));
            return false;
        });
         $("a[name=Delete]").click(function(event) {
            event = event || window.event;
            if(!confirm('确定要删除该账户申请吗？')) {
                event.preventDefault();
                return false;
            }
        });
        
    });
</script>
}

QsTech.Framework.Web/Modules/QsTech.Accounts/Views/RegisterAccount/View.cshtml
@model QsTech.Accounts.Models.Accounts.EditAccountModel
@{
    this.ChannelId = "Management";
    ViewBag.Title = "账户申请审核";
    var success = ViewBag.Success ?? false;
}
<div class="rightCont">
    <div class="mt10">
       
            <table style="width:100%;" class="data-detail">
                <tr>
                    <td align="right" width="10%">姓名：</td>
                    <td width="20%">
                        <h1 style="font-size: 20px;color:#d80f32;">@Model.Name</h1>
                        @Html.HiddenFor(model => model.Id)
                    </td>
                    <td style="text-align: right;" width="10%">
                         性别：
                    </td>
                    <td>
                        @Model.Gender
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;">
                        <i class="required"></i>移动电话：
                    </td>
                    <td>
                       @Model.Mobile
                    </td>
                    <td style="text-align: right;">
                      电子邮件：
                    </td>
                    <td>
                      @Model.Email
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right; vertical-align: top;">
                        公司信息:
                    </td>
                    <td colspan="3">
                       @Html.Raw(Model.Remark)
                    </td>
                </tr>
            </table>
            <div class="mt_10 ml_20">
                <input type="button" value="创建账户" onclick="javascript:window.location.href='@Url.Action("AuthorizeRegisterAccount")?id=@Model.Id'" class="btn btn-primary ml_20" />
                <input type="button" value="账户申请列表" class="btn" onclick="javascript:window.location.href='@Url.Action("List")'" />
            </div>
    </div>
</div>
@section AfterBody
{
@ResourceManager.Include("modalShow").Render()
<script type="text/javascript">
    $(function () {
        $("#Birthday").datepicker({ altFormat: 'yy-mm-dd', yearRange:'c-50' });
        $(".btn_gray").attr("disabled","");

      
    });
</script>
}